//! Builds `codepack-cli` and generates the files the Linux packages need beside it —
//! shell completions and a man page — so `tauri.conf.json`'s `deb.files`/`rpm.files`
//! have something already on disk to point at before `tauri build` runs (audit
//! 2026-09-07, L-1/L-10).
//!
//! `codepack-cli` has no library target (`.ai/project/12-domain-rules.md`'s binaries
//! stay thin, and this one has no caller to justify one), so these are generated by
//! running the compiled binary itself — `codepack completions <shell>` and the hidden
//! `codepack manpage` — rather than by linking against its argument-parsing code.
//!
//! `CODEPACK_CLI_PREBUILT` (any value, checked for presence only): skip building
//! `codepack-cli` here and trust that `target/release/codepack` already exists. CI sets
//! this after cross-building the CLI inside an older-glibc container (audit 2026-09-07
//! remediation, found 2026-09-08): a `codepack` built natively on `ubuntu-latest`
//! (glibc 2.39) references `pidfd_spawnp`/`pidfd_getpid` under glibc's own weak-symbol
//! convention, but the *version* those symbols belong to still has to exist in the
//! runtime's glibc for dynamic linking to succeed at all — and Debian 12 (glibc 2.36,
//! the oldest distro `install-and-run-linux`'s matrix validates against) does not have
//! it, so the installed CLI refused to even start there
//! (`version 'GLIBC_2.39' not found`). Building instead inside a `debian:12` container
//! (see `.github/workflows/package-linux.yml` and `release.yml`) produces a binary
//! glibc's own backward-compatibility guarantee lets run everywhere newer too —
//! confirmed by hand against real `debian:12`, `ubuntu:24.04` and `fedora:41`
//! containers before writing this fix, not assumed. Not applied to the Tauri desktop
//! binary in the same pass: `install-and-run-linux`'s GUI-under-Xvfb check is
//! `continue-on-error` (soft, per its own comment), and cross-building the whole
//! webview stack for an older base image is a meaningfully bigger, separately-risked
//! change — recorded as narrower known debt in `docs/architecture/overview.md` rather
//! than silently left unfixed.

use std::path::Path;
use std::process::Command;

/// Where the generated files live, relative to the repository root — a `target/`
/// subdirectory, so it needs no `.gitignore` entry of its own and `clean-project`
/// already treats it as disposable build output.
const ASSETS_DIR: &str = "target/packaging-assets";

fn cli_binary_name() -> &'static str {
    if cfg!(windows) {
        "codepack.exe"
    } else {
        "codepack"
    }
}

/// Builds `codepack-cli` in release mode and generates its completions and man page
/// into [`ASSETS_DIR`]. Only meaningful on Linux, where `tauri.conf.json` actually
/// references these paths (`deb`/`rpm` targets); a no-op elsewhere so `cargo xtask
/// package` does not pay for a build nothing will read on Windows or macOS.
///
/// What this produces, and where `tauri.conf.json`'s `deb.files`/`rpm.files` expect to
/// find it (paths there are relative to `apps/desktop/src-tauri`, so three `../` reach
/// the repository root — a detail worth restating here, since Tauri resolves that path
/// itself and a directory move would break it silently otherwise):
///
/// | in the package                                       | written here as                          |
/// |-------------------------------------------------------|-----------------------------------------|
/// | `/usr/bin/codepack`                                    | `target/release/codepack` (by `cargo auditable build`, not this function) |
/// | `/usr/share/bash-completion/completions/codepack`       | `target/packaging-assets/codepack.bash`  |
/// | `/usr/share/zsh/site-functions/_codepack`               | `target/packaging-assets/_codepack`      |
/// | `/usr/share/fish/vendor_completions.d/codepack.fish`    | `target/packaging-assets/codepack.fish`  |
/// | `/usr/share/man/man1/codepack.1.gz`                     | `target/packaging-assets/codepack.1.gz`  |
pub(crate) fn prepare(root: &Path) -> Result<(), String> {
    if !cfg!(target_os = "linux") {
        return Ok(());
    }

    let cli_binary = root.join("target/release").join(cli_binary_name());
    let prebuilt = std::env::var_os("CODEPACK_CLI_PREBUILT").is_some();
    ensure_cli_binary(root, &cli_binary, prebuilt)?;

    let assets_dir = root.join(ASSETS_DIR);
    std::fs::create_dir_all(&assets_dir)
        .map_err(|error| format!("cannot create {}: {error}", assets_dir.display()))?;

    write_command_stdout(
        &cli_binary,
        &["completions", "bash"],
        &assets_dir.join("codepack.bash"),
    )?;
    write_command_stdout(
        &cli_binary,
        &["completions", "zsh"],
        &assets_dir.join("_codepack"),
    )?;
    write_command_stdout(
        &cli_binary,
        &["completions", "fish"],
        &assets_dir.join("codepack.fish"),
    )?;

    let manpage = assets_dir.join("codepack.1");
    write_command_stdout(&cli_binary, &["manpage"], &manpage)?;
    // `usr/share/man/man1/*.1.gz` is the convention `dpkg`/`rpm` both expect man pages
    // in; an uncompressed page installs but `man codepack` would not find it without
    // the extension a package manager looks for. Shelled out to the system's own
    // `gzip` rather than a new Rust dependency (`flate2` or similar) pulled in for one
    // call site that only ever runs in a Linux packaging job where `gzip` is as safe an
    // assumption as `dpkg-deb` already is a few steps later.
    run(
        Command::new("gzip").current_dir(&assets_dir).args([
            "-f", // Re-running `package` must overwrite a stale `.gz`, not refuse.
            "codepack.1",
        ]),
        "gzip codepack.1",
    )?;

    Ok(())
}

/// Either trusts an already-built `cli_binary` (`prebuilt`) or builds it natively with
/// `cargo auditable` (audit 2026-09-07, S-10: embeds the `.dep-v0` linker section
/// `cargo audit bin` reads directly, the cheap half of "what is inside this file" for a
/// product whose own job is reasoning about a supply chain). Split out of [`prepare`]
/// so the `prebuilt` branch — refusing a missing file with a reason naming
/// `CODEPACK_CLI_PREBUILT` — is unit-testable without needing a real Linux build or a
/// process-global environment variable mutation in the test itself.
fn ensure_cli_binary(root: &Path, cli_binary: &Path, prebuilt: bool) -> Result<(), String> {
    if prebuilt {
        return if cli_binary.is_file() {
            Ok(())
        } else {
            Err(format!(
                "CODEPACK_CLI_PREBUILT is set but {} does not exist — the CI step that \
                 cross-builds codepack-cli against an older glibc baseline (see \
                 .github/workflows/package-linux.yml) must run and produce this file \
                 before `cargo xtask package` continues",
                cli_binary.display()
            ))
        };
    }

    run(
        Command::new("cargo").current_dir(root).args([
            "auditable",
            "build",
            "--release",
            "-p",
            "codepack-cli",
        ]),
        "cargo auditable build -p codepack-cli",
    )?;

    if !cli_binary.is_file() {
        return Err(format!(
            "cargo auditable build succeeded but {} does not exist",
            cli_binary.display()
        ));
    }
    Ok(())
}

fn write_command_stdout(binary: &Path, args: &[&str], destination: &Path) -> Result<(), String> {
    let label = format!("{} {}", binary.display(), args.join(" "));
    let output = Command::new(binary)
        .args(args)
        .output()
        .map_err(|error| format!("{label}: failed to launch: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "{label}: exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    std::fs::write(destination, &output.stdout)
        .map_err(|error| format!("cannot write {}: {error}", destination.display()))?;
    Ok(())
}

fn run(command: &mut Command, label: &str) -> Result<(), String> {
    println!("$ {label}");
    let status = command
        .status()
        .map_err(|error| format!("{label}: failed to launch: {error}"))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("{label}: exited with {status}"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// `CARGO` is set by cargo itself for every process it launches (including this
    /// test binary), so this is a real, portable command to capture output from —
    /// no assumption about what else is on `PATH`, and no dependency on
    /// `codepack-cli` having been built first.
    fn cargo_binary() -> PathBuf {
        std::env::var_os("CARGO")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("cargo"))
    }

    #[test]
    fn write_command_stdout_captures_stdout_to_a_file() {
        let dir = tempfile::tempdir().unwrap();
        let destination = dir.path().join("version.txt");

        write_command_stdout(&cargo_binary(), &["--version"], &destination).unwrap();

        let content = std::fs::read_to_string(&destination).unwrap();
        assert!(
            content.starts_with("cargo "),
            "unexpected output: {content}"
        );
    }

    /// The failure this exists to catch: a command that fails partway must not leave a
    /// truncated or garbage file behind for the packaging step to silently bundle.
    #[test]
    fn write_command_stdout_reports_failure_and_writes_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let destination = dir.path().join("out.txt");

        let error = write_command_stdout(
            &cargo_binary(),
            &["not-a-real-cargo-subcommand-xyz"],
            &destination,
        )
        .unwrap_err();

        assert!(error.contains("exited with"), "{error}");
        assert!(!destination.exists());
    }

    #[test]
    fn run_reports_a_nonzero_exit_by_name_rather_than_silently_succeeding() {
        let error = run(
            Command::new(cargo_binary()).arg("not-a-real-cargo-subcommand-xyz"),
            "cargo not-a-real-cargo-subcommand-xyz",
        )
        .unwrap_err();
        assert!(error.contains("cargo not-a-real-cargo-subcommand-xyz"));
    }

    #[test]
    fn cli_binary_name_carries_the_platform_exe_suffix() {
        assert_eq!(
            cli_binary_name(),
            if cfg!(windows) {
                "codepack.exe"
            } else {
                "codepack"
            }
        );
    }

    #[test]
    fn ensure_cli_binary_accepts_an_existing_prebuilt_binary_without_rebuilding() {
        let dir = tempfile::tempdir().unwrap();
        let binary = dir.path().join("codepack");
        std::fs::write(&binary, b"stand-in for a real cross-built binary").unwrap();

        // `root` is deliberately a different, nonexistent directory: the prebuilt
        // branch must never touch `cargo`/`root` at all, so a bogus root cannot break it.
        ensure_cli_binary(Path::new("/does/not/exist"), &binary, true).unwrap();
    }

    #[test]
    fn ensure_cli_binary_refuses_a_missing_prebuilt_binary_naming_the_env_var() {
        let dir = tempfile::tempdir().unwrap();
        let binary = dir.path().join("codepack");

        let error = ensure_cli_binary(Path::new("/does/not/exist"), &binary, true).unwrap_err();

        assert!(error.contains("CODEPACK_CLI_PREBUILT"), "{error}");
        assert!(!binary.exists());
    }
}
