//! Builds `codepack-cli` and generates the files the Linux packages need beside it —
//! shell completions and a man page — so `tauri.conf.json`'s `deb.files`/`rpm.files`
//! have something already on disk to point at before `tauri build` runs (audit
//! 2026-09-07, L-1/L-10).
//!
//! `codepack-cli` has no library target (`.ai/project/12-domain-rules.md`'s binaries
//! stay thin, and this one has no caller to justify one), so these are generated by
//! running the compiled binary itself — `codepack completions <shell>` and the hidden
//! `codepack manpage` — rather than by linking against its argument-parsing code.

use std::path::Path;
use std::process::Command;

/// Where the generated files live, relative to the repository root — a `target/`
/// subdirectory, so it needs no `.gitignore` entry of its own and `clean-project`
/// already treats it as disposable build output.
const ASSETS_DIR: &str = "target/packaging-assets";

fn cli_binary_name() -> &'static str {
    if cfg!(windows) {
        "codepack.exe"
    } else {
        "codepack"
    }
}

/// Builds `codepack-cli` in release mode and generates its completions and man page
/// into [`ASSETS_DIR`]. Only meaningful on Linux, where `tauri.conf.json` actually
/// references these paths (`deb`/`rpm` targets); a no-op elsewhere so `cargo xtask
/// package` does not pay for a build nothing will read on Windows or macOS.
///
/// What this produces, and where `tauri.conf.json`'s `deb.files`/`rpm.files` expect to
/// find it (paths there are relative to `apps/desktop/src-tauri`, so three `../` reach
/// the repository root — a detail worth restating here, since Tauri resolves that path
/// itself and a directory move would break it silently otherwise):
///
/// | in the package                                       | written here as                          |
/// |-------------------------------------------------------|-----------------------------------------|
/// | `/usr/bin/codepack`                                    | `target/release/codepack` (by `cargo auditable build`, not this function) |
/// | `/usr/share/bash-completion/completions/codepack`       | `target/packaging-assets/codepack.bash`  |
/// | `/usr/share/zsh/site-functions/_codepack`               | `target/packaging-assets/_codepack`      |
/// | `/usr/share/fish/vendor_completions.d/codepack.fish`    | `target/packaging-assets/codepack.fish`  |
/// | `/usr/share/man/man1/codepack.1.gz`                     | `target/packaging-assets/codepack.1.gz`  |
pub(crate) fn prepare(root: &Path) -> Result<(), String> {
    if !cfg!(target_os = "linux") {
        return Ok(());
    }

    // `auditable` rather than a plain build (audit 2026-09-07, S-10): this is the
    // binary a `.deb`/`.rpm` actually ships at `/usr/bin/codepack`, and embedding its
    // dependency list (a `.dep-v0` linker section `cargo audit bin` reads directly) is
    // the cheap half of "what is inside this file" for a product whose own job is
    // reasoning about a supply chain. Needs the `cargo-auditable` subcommand on PATH —
    // CI installs it the same way it already installs `cargo-deny`.
    run(
        Command::new("cargo").current_dir(root).args([
            "auditable",
            "build",
            "--release",
            "-p",
            "codepack-cli",
        ]),
        "cargo auditable build -p codepack-cli",
    )?;

    let cli_binary = root.join("target/release").join(cli_binary_name());
    if !cli_binary.is_file() {
        return Err(format!(
            "cargo auditable build succeeded but {} does not exist",
            cli_binary.display()
        ));
    }

    let assets_dir = root.join(ASSETS_DIR);
    std::fs::create_dir_all(&assets_dir)
        .map_err(|error| format!("cannot create {}: {error}", assets_dir.display()))?;

    write_command_stdout(
        &cli_binary,
        &["completions", "bash"],
        &assets_dir.join("codepack.bash"),
    )?;
    write_command_stdout(
        &cli_binary,
        &["completions", "zsh"],
        &assets_dir.join("_codepack"),
    )?;
    write_command_stdout(
        &cli_binary,
        &["completions", "fish"],
        &assets_dir.join("codepack.fish"),
    )?;

    let manpage = assets_dir.join("codepack.1");
    write_command_stdout(&cli_binary, &["manpage"], &manpage)?;
    // `usr/share/man/man1/*.1.gz` is the convention `dpkg`/`rpm` both expect man pages
    // in; an uncompressed page installs but `man codepack` would not find it without
    // the extension a package manager looks for. Shelled out to the system's own
    // `gzip` rather than a new Rust dependency (`flate2` or similar) pulled in for one
    // call site that only ever runs in a Linux packaging job where `gzip` is as safe an
    // assumption as `dpkg-deb` already is a few steps later.
    run(
        Command::new("gzip").current_dir(&assets_dir).args([
            "-f", // Re-running `package` must overwrite a stale `.gz`, not refuse.
            "codepack.1",
        ]),
        "gzip codepack.1",
    )?;

    Ok(())
}

fn write_command_stdout(binary: &Path, args: &[&str], destination: &Path) -> Result<(), String> {
    let label = format!("{} {}", binary.display(), args.join(" "));
    let output = Command::new(binary)
        .args(args)
        .output()
        .map_err(|error| format!("{label}: failed to launch: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "{label}: exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    std::fs::write(destination, &output.stdout)
        .map_err(|error| format!("cannot write {}: {error}", destination.display()))?;
    Ok(())
}

fn run(command: &mut Command, label: &str) -> Result<(), String> {
    println!("$ {label}");
    let status = command
        .status()
        .map_err(|error| format!("{label}: failed to launch: {error}"))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("{label}: exited with {status}"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// `CARGO` is set by cargo itself for every process it launches (including this
    /// test binary), so this is a real, portable command to capture output from —
    /// no assumption about what else is on `PATH`, and no dependency on
    /// `codepack-cli` having been built first.
    fn cargo_binary() -> PathBuf {
        std::env::var_os("CARGO")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("cargo"))
    }

    #[test]
    fn write_command_stdout_captures_stdout_to_a_file() {
        let dir = tempfile::tempdir().unwrap();
        let destination = dir.path().join("version.txt");

        write_command_stdout(&cargo_binary(), &["--version"], &destination).unwrap();

        let content = std::fs::read_to_string(&destination).unwrap();
        assert!(
            content.starts_with("cargo "),
            "unexpected output: {content}"
        );
    }

    /// The failure this exists to catch: a command that fails partway must not leave a
    /// truncated or garbage file behind for the packaging step to silently bundle.
    #[test]
    fn write_command_stdout_reports_failure_and_writes_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let destination = dir.path().join("out.txt");

        let error = write_command_stdout(
            &cargo_binary(),
            &["not-a-real-cargo-subcommand-xyz"],
            &destination,
        )
        .unwrap_err();

        assert!(error.contains("exited with"), "{error}");
        assert!(!destination.exists());
    }

    #[test]
    fn run_reports_a_nonzero_exit_by_name_rather_than_silently_succeeding() {
        let error = run(
            Command::new(cargo_binary()).arg("not-a-real-cargo-subcommand-xyz"),
            "cargo not-a-real-cargo-subcommand-xyz",
        )
        .unwrap_err();
        assert!(error.contains("cargo not-a-real-cargo-subcommand-xyz"));
    }

    #[test]
    fn cli_binary_name_carries_the_platform_exe_suffix() {
        assert_eq!(
            cli_binary_name(),
            if cfg!(windows) {
                "codepack.exe"
            } else {
                "codepack"
            }
        );
    }
}
