from __future__ import annotations

import json
from dataclasses import asdict

from ..config import Config
from ..constants import APP_NAME, APP_VERSION, IGNORED_DIR_NAMES, REPORT_DESCRIPTIONS
from ..models import CopyStats, ExportPaths, TextDumpStats
from ..utils.time_utils import human_now

def write_manifest(
    paths: ExportPaths,
    config: Config,
    copy_stats: CopyStats,
    text_stats: TextDumpStats,
    extra_ignored_dirs: frozenset[str] | set[str],
    cancelled: bool,
) -> None:
    """Write a machine-readable description of the bundle."""
    data = {
        "app": APP_NAME,
        "app_version": APP_VERSION,
        "generated_at": human_now(),
        "bundle_name": paths.bundle_name,
        "source_root": str(paths.source_root),
        "project_name": paths.project_name,
        "cancelled": cancelled,
        "settings": {
            "max_text_file_mb": config.max_text_file_mb,
            "redact_secrets": config.redact_secrets,
            "keep_staging_folder": config.keep_staging_folder,
            "include_project_in_zip": config.include_project_in_zip,
            "export_profile": config.normalized_export_profile(),
        },
        "ignored_dirs": {
            "defaults": sorted(IGNORED_DIR_NAMES),
            "user_extras": sorted(set(extra_ignored_dirs) - IGNORED_DIR_NAMES),
            "effective": sorted(IGNORED_DIR_NAMES | set(extra_ignored_dirs)),
        },
        "notes": [
            "Git data is collected from the ORIGINAL project; the .git "
            "directory is never copied into the bundle.",
            "All other reports describe the copied project (see "
            f"'{paths.project_name}/' inside the bundle).",
            "Symlinks were skipped during copy to avoid accidental escape "
            "from the project tree.",
        ],
        "stats": {
            "copy": asdict(copy_stats),
            "text_dump": asdict(text_stats),
        },
        "layout": {
            "project_dir": paths.project_name + "/",
            "project_profile": "PROJECT_PROFILE.json",
            "reports": [path for path, _desc in REPORT_DESCRIPTIONS],
        },
    }

    paths.manifest_file.write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

def write_index_md(
    paths: ExportPaths,
    config: Config,
    extra_ignored_dirs: frozenset[str] | set[str],
) -> None:
    """Write a human-readable bundle table of contents."""
    ignored_effective = sorted(IGNORED_DIR_NAMES | set(extra_ignored_dirs))

    with paths.index_file.open("w", encoding="utf-8", newline="\n") as out:
        out.write(f"# Export bundle: `{paths.project_name}`\n\n")
        out.write(f"_Generated by {APP_NAME} v{APP_VERSION} on {human_now()}._\n\n")
        out.write(
            "This archive bundles a copy of a project together with a set of "
            "machine- and human-readable reports describing it from several "
            "angles.\n\n"
        )

        out.write("## Bundle contents\n\n")
        out.write(
            f"- `{paths.project_name}/` — working copy of the project "
            f"(without `.git`, `node_modules`, and any user-configured extras).\n"
        )
        out.write("- `manifest.json` — machine-readable metadata about this export.\n")
        out.write("- `reports/` — generated reports (see below).\n\n")

        out.write("## Reports\n\n")
        for rel_path, description in REPORT_DESCRIPTIONS:
            out.write(f"- `{rel_path}` — {description}\n")

        out.write("\n## Settings used for this export\n\n")
        out.write(f"- Max text-file size: **{config.max_text_file_mb} MB**\n")
        out.write(
            f"- Secret redaction: "
            f"**{'enabled' if config.redact_secrets else 'disabled'}**\n"
        )
        out.write(
            f"- Project included in ZIP: "
            f"**{'yes' if config.include_project_in_zip else 'no (reports only)'}**\n"
        )
        out.write(
            f"- Staging folder kept on Desktop: "
            f"**{'yes' if config.keep_staging_folder else 'no'}**\n"
        )
        out.write(
            f"- Ignored directories: "
            + ", ".join(f"`{n}`" for n in ignored_effective)
            + "\n"
        )

        out.write("\n## Notes\n\n")
        out.write(
            "- Git data was collected from the **original** project. The "
            "`.git` directory itself is intentionally not part of the bundle.\n"
        )
        out.write(
            "- All other reports describe the **copy** of the project that "
            f"lives in `{paths.project_name}/` inside this bundle.\n"
        )
        out.write(
            "- Symbolic links were skipped during the copy to avoid accidental "
            "escape from the project tree.\n"
        )
