# Core application module for codepack.

from __future__ import annotations

import re
from pathlib import Path

APP_NAME = "Project Exporter Desktop"

APP_VERSION = "5.1.0"

SETTINGS_FILE = Path.home() / ".project_exporter_desktop.json"

USER_EXPORT_PROFILES_FILE = Path.home() / ".project_exporter_profiles.json"

MAX_ARCHIVE_PART_MB = 512
MAX_ARCHIVE_PART_BYTES = MAX_ARCHIVE_PART_MB * 1024 * 1024
ARCHIVE_PART_TARGET_BYTES = 500 * 1024 * 1024

IGNORED_DIR_NAMES: frozenset[str] = frozenset(
    {
        ".git",
        "node_modules",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".tox",
        ".venv",
        "venv",
        "env",
        "dist",
        "build",
        "coverage",
        ".coverage",
        ".next",
        ".nuxt",
        ".turbo",
        ".parcel-cache",
    }
)

TEXT_EXTENSIONS: set[str] = {
    "adoc",
    "ahk",
    "asciidoc",
    "astro",
    "bash",
    "bat",
    "bib",
    "bzl",
    "c",
    "cc",
    "cfg",
    "cjs",
    "clj",
    "cljc",
    "cljs",
    "cls",
    "cmake",
    "cmd",
    "conf",
    "config",
    "cpp",
    "cs",
    "css",
    "csv",
    "cxx",
    "d",
    "dart",
    "desktop",
    "diff",
    "dockerfile",
    "dockerignore",
    "editorconfig",
    "edn",
    "ejs",
    "elm",
    "env",
    "erl",
    "err",
    "ex",
    "exs",
    "feature",
    "fish",
    "fs",
    "fsi",
    "fsx",
    "gemspec",
    "gitattributes",
    "gitignore",
    "go",
    "gql",
    "gradle",
    "graphql",
    "groovy",
    "h",
    "haml",
    "hcl",
    "hh",
    "hpp",
    "hrl",
    "hs",
    "htm",
    "html",
    "hxx",
    "ini",
    "ipynb",
    "java",
    "jl",
    "js",
    "json",
    "json5",
    "jsx",
    "kt",
    "kts",
    "less",
    "lhs",
    "lock",
    "log",
    "lua",
    "makefile",
    "md",
    "markdown",
    "mjs",
    "mk",
    "ml",
    "mli",
    "nim",
    "npmrc",
    "nvmrc",
    "odin",
    "org",
    "out",
    "patch",
    "php",
    "phtml",
    "pl",
    "pm",
    "pod",
    "properties",
    "proto",
    "ps1",
    "psm1",
    "py",
    "pyi",
    "pyw",
    "r",
    "rake",
    "rb",
    "rs",
    "rst",
    "sass",
    "scala",
    "scss",
    "sh",
    "sol",
    "sql",
    "svelte",
    "tex",
    "tf",
    "tfvars",
    "toml",
    "ts",
    "tsv",
    "tsx",
    "txt",
    "v",
    "vb",
    "vbs",
    "vue",
    "xml",
    "yaml",
    "yml",
    "zig",
    "zsh",
}

TEXT_FILENAMES_WITHOUT_EXTENSION: set[str] = {
    ".env",
    ".env.example",
    ".env.local",
    ".env.development",
    ".env.production",
    ".gitignore",
    ".gitattributes",
    ".dockerignore",
    ".editorconfig",
    ".npmrc",
    ".nvmrc",
    "dockerfile",
    "makefile",
    "readme",
    "license",
}

BINARY_EXTENSIONS: set[str] = {
    "7z",
    "a",
    "aac",
    "accdb",
    "ai",
    "aiff",
    "apk",
    "avi",
    "bin",
    "blend",
    "bmp",
    "bz2",
    "cab",
    "class",
    "db",
    "dll",
    "dmg",
    "doc",
    "docx",
    "dwg",
    "dylib",
    "ear",
    "eot",
    "epub",
    "exe",
    "fbx",
    "flac",
    "flv",
    "gif",
    "gz",
    "heic",
    "ico",
    "iso",
    "jar",
    "jpeg",
    "jpg",
    "lib",
    "m4a",
    "m4v",
    "max",
    "mdb",
    "mkv",
    "mov",
    "mp3",
    "mp4",
    "mpeg",
    "mpg",
    "o",
    "obj",
    "odp",
    "ods",
    "odt",
    "ogg",
    "opus",
    "otf",
    "pdf",
    "png",
    "ppt",
    "pptx",
    "psd",
    "pyc",
    "pyd",
    "pyo",
    "rar",
    "raw",
    "so",
    "sqlite",
    "sqlite3",
    "tar",
    "tif",
    "tiff",
    "ttf",
    "wav",
    "war",
    "webm",
    "webp",
    "wmv",
    "woff",
    "woff2",
    "wma",
    "xls",
    "xlsx",
    "xz",
    "zip",
}

TRY_ENCODINGS: tuple[str, ...] = (
    "utf-8",
    "utf-8-sig",
    "cp1251",
    "cp866",
    "utf-16",
    "latin-1",
)

_REDACT_KEYWORDS = r"API[_-]?KEY|SECRET|TOKEN|PASSWORD|PASS|PRIVATE[_-]?KEY"

_SCAN_KEYWORDS = (
    _REDACT_KEYWORDS + r"|DATABASE[_-]?URL|JWT[_-]?SECRET|ACCESS[_-]?KEY|CLIENT[_-]?SECRET"
)

SECRET_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(rf"(?i)\b({_REDACT_KEYWORDS})\b\s*[:=]\s*(['\"]?)[^\s'\"\n]+(\2)"),
    re.compile(r"(?i)\b(BEARER)\s+[A-Za-z0-9._\-+/=]{16,}"),
)

SECRET_KEY_PATTERN = re.compile(rf"(?i)\b({_SCAN_KEYWORDS})\b")

TODO_PATTERN = re.compile(r"(?i)\b(TODO|FIXME|HACK|XXX|BUG|TEMP|REFACTOR|DEPRECATED)\b")

MONTHS = (
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
)

LANGUAGE_BY_EXTENSION: dict[str, str] = {
    "py": "Python",
    "pyw": "Python",
    "pyi": "Python",
    "js": "JavaScript",
    "jsx": "JavaScript / React",
    "mjs": "JavaScript",
    "cjs": "JavaScript",
    "ts": "TypeScript",
    "tsx": "TypeScript / React",
    "css": "CSS",
    "scss": "SCSS",
    "sass": "Sass",
    "less": "Less",
    "html": "HTML",
    "htm": "HTML",
    "vue": "Vue",
    "svelte": "Svelte",
    "astro": "Astro",
    "go": "Go",
    "rs": "Rust",
    "java": "Java",
    "kt": "Kotlin",
    "kts": "Kotlin",
    "cs": "C#",
    "cpp": "C++",
    "cxx": "C++",
    "cc": "C++",
    "c": "C",
    "h": "C/C++ Header",
    "hpp": "C++ Header",
    "rb": "Ruby",
    "php": "PHP",
    "swift": "Swift",
    "dart": "Dart",
    "sql": "SQL",
    "sh": "Shell",
    "bash": "Shell",
    "zsh": "Shell",
    "fish": "Shell",
    "ps1": "PowerShell",
    "bat": "Batch",
    "cmd": "Batch",
    "json": "JSON",
    "json5": "JSON5",
    "yaml": "YAML",
    "yml": "YAML",
    "toml": "TOML",
    "xml": "XML",
    "md": "Markdown",
    "markdown": "Markdown",
    "rst": "reStructuredText",
    "dockerfile": "Dockerfile",
}

SOURCE_CODE_EXTENSIONS: set[str] = {
    "astro",
    "c",
    "cc",
    "cpp",
    "cs",
    "css",
    "cxx",
    "dart",
    "go",
    "h",
    "hpp",
    "html",
    "htm",
    "java",
    "js",
    "jsx",
    "kt",
    "kts",
    "less",
    "mjs",
    "php",
    "py",
    "pyi",
    "pyw",
    "rb",
    "rs",
    "sass",
    "scss",
    "sh",
    "sql",
    "svelte",
    "ts",
    "tsx",
    "vue",
}

CONFIG_FILES: tuple[str, ...] = (
    "package.json",
    "pnpm-lock.yaml",
    "package-lock.json",
    "yarn.lock",
    "bun.lockb",
    "tsconfig.json",
    "jsconfig.json",
    "vite.config.ts",
    "vite.config.js",
    "next.config.js",
    "next.config.mjs",
    "next.config.ts",
    "eslint.config.js",
    "eslint.config.mjs",
    ".eslintrc",
    ".eslintrc.js",
    ".eslintrc.json",
    ".prettierrc",
    ".prettierrc.json",
    "prettier.config.js",
    "tailwind.config.js",
    "tailwind.config.ts",
    "postcss.config.js",
    "components.json",
    "pyproject.toml",
    "requirements.txt",
    "requirements-dev.txt",
    "poetry.lock",
    "Pipfile",
    "Pipfile.lock",
    "go.mod",
    "go.sum",
    "Cargo.toml",
    "Cargo.lock",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    ".env.example",
    ".gitignore",
    "README.md",
    "LICENSE",
)

SENSITIVE_FILENAMES: set[str] = {
    ".env",
    ".env.local",
    ".env.development",
    ".env.production",
    ".env.test",
    "id_rsa",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "credentials.json",
    "service-account.json",
    "service_account.json",
    "firebase-adminsdk.json",
}

SENSITIVE_SUFFIXES: set[str] = {
    "key",
    "pem",
    "p12",
    "pfx",
    "crt",
    "cer",
    "keystore",
    "jks",
}


DEFAULT_EXPORT_PROFILE = "full"

EXPORT_PROFILES: dict[str, str] = {
    "quick": "Быстрый — краткий обзор, инструкции по запуску, ключевые файлы и профиль проекта.",
    "full": "Полный — все созданные отчёты и файлы AI-контекста.",
    "ai_review": "AI-ревью — все отчёты для понимания проекта ChatGPT/Codex и безопасного изменения кода.",
    "security": "Безопасность — конфигурация, зависимости, Git, качество кода и отчёты безопасности.",
    "minimal": "Минимальный — компактный обзор для лёгкой передачи.",
}

SAFE_EXPORT_MODES: dict[str, str] = {
    "safe": "Строгий — исключает секреты, приватные ключи, локальные БД, дампы и архивы.",
    "balanced": "Сбалансированный — исключает высокорисковые ключи и учётные данные, сохраняет больше конфигурации.",
    "full": "Полный — копирует файлы проекта, кроме игнорируемых директорий; только для приватных/локальных экспортов.",
}

DIFF_EXPORT_MODES: dict[str, str] = {
    "all": "Полный экспорт — экспортировать весь выбранный проект.",
    "last_export": "С последнего экспорта — сравнить текущие хэши с историей экспортов.",
    "git_ref": "С Git-ссылки — экспортировать изменения относительно ветки, тега или коммита.",
    "uncommitted": "Только uncommitted — изменения рабочего дерева и новые файлы.",
}

HIGH_RISK_FILENAMES: set[str] = {
    ".env",
    ".env.local",
    ".env.development",
    ".env.production",
    ".env.test",
    ".npmrc",
    ".pypirc",
    "credentials.json",
    "secrets.json",
    "secret.json",
    "service-account.json",
    "service_account.json",
    "firebase-adminsdk.json",
    "id_rsa",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
}

SAFE_MODE_EXCLUDED_SUFFIXES: set[str] = SENSITIVE_SUFFIXES | {
    "db",
    "sqlite",
    "sqlite3",
    "bak",
    "dump",
    "backup",
    "7z",
    "rar",
    "tar",
    "gz",
    "xz",
    "zip",
}

BALANCED_MODE_EXCLUDED_SUFFIXES: set[str] = SENSITIVE_SUFFIXES | {
    "bak",
    "dump",
    "backup",
}

AI_PRESETS: dict[str, dict[str, object]] = {
    "Claude Code": {
        "description": "Полный контекст: архитектура, Git-история, все AI-отчёты. Оптимально для Claude.",
        "export_profile": "ai_review",
        "safe_export_mode": "safe",
        "redact_secrets": True,
        "include_git_patch": False,
        "diff_export_mode": "all",
        "text_file_size_limit_enabled": False,
    },
    "ChatGPT": {
        "description": "Компактный обзор без Git-патча. Подходит для GPT-4 с ограниченным контекстным окном.",
        "export_profile": "quick",
        "safe_export_mode": "safe",
        "redact_secrets": True,
        "include_git_patch": False,
        "diff_export_mode": "all",
        "text_file_size_limit_enabled": True,
        "max_text_file_mb": 1,
    },
    "Code Review": {
        "description": "Полный снимок кода с Git-патчем. Идеально для детального ревью.",
        "export_profile": "ai_review",
        "safe_export_mode": "balanced",
        "redact_secrets": True,
        "include_git_patch": True,
        "diff_export_mode": "all",
        "text_file_size_limit_enabled": False,
    },
    "Security Audit": {
        "description": "Акцент на безопасности: конфигурация, зависимости и анализ рисков.",
        "export_profile": "security",
        "safe_export_mode": "safe",
        "redact_secrets": True,
        "include_git_patch": False,
        "diff_export_mode": "all",
        "text_file_size_limit_enabled": False,
    },
    "Онбординг": {
        "description": "Краткий обзор для быстрого введения нового разработчика в проект.",
        "export_profile": "minimal",
        "safe_export_mode": "balanced",
        "redact_secrets": True,
        "include_git_patch": False,
        "diff_export_mode": "all",
        "text_file_size_limit_enabled": True,
        "max_text_file_mb": 2,
    },
}

REPORT_DESCRIPTIONS: tuple[tuple[str, str], ...] = (
    (
        "PROJECT_PROFILE.json",
        "Machine-readable project passport: stack, commands, entrypoints, capabilities, risk level.",
    ),
    (
        "reports/01_structure.txt",
        "PowerShell-like directory listing of the copied project.",
    ),
    (
        "reports/02_git.txt",
        "Read-only Git snapshot from the ORIGINAL project (status, last commits).",
    ),
    (
        "reports/03_text_dump.txt",
        "Concatenated contents of every text-like file in the copy.",
    ),
    (
        "reports/insights/00_project_profile.json",
        "Copy of the machine-readable project profile inside the insights folder.",
    ),
    (
        "reports/insights/01_summary.txt",
        "High-level overview: stack detection, language counts, biggest files.",
    ),
    (
        "reports/insights/02_file_statistics.txt",
        "File counts by extension, deepest paths, empty / suspicious files.",
    ),
    (
        "reports/insights/03_dependencies.txt",
        "package.json / requirements.txt / go.mod / Cargo.toml dependencies.",
    ),
    (
        "reports/insights/04_scripts.txt",
        "npm/pnpm scripts, Makefile targets, Docker convenience commands.",
    ),
    (
        "reports/insights/05_git_deep.txt",
        "Extended read-only Git inspection (branches, remotes, diffs, ls-files).",
    ),
    (
        "reports/insights/06_security_scan.txt",
        "Heuristic scan for .env-like files, secret-looking lines, and risky code patterns.",
    ),
    (
        "reports/insights/07_todo_fixme.txt",
        "TODO / FIXME / HACK / XXX / DEPRECATED markers across the codebase.",
    ),
    (
        "reports/insights/08_code_metrics.txt",
        "LOC, comment ratios, files over 500 / 1000 lines.",
    ),
    (
        "reports/insights/09_config.txt",
        "Detected configuration files and capability checklist.",
    ),
    ("reports/insights/10_docker.txt", "Dockerfile / docker-compose service map."),
    (
        "reports/insights/11_routes_and_pages.txt",
        "Heuristic UI map: routes, pages, components.",
    ),
    (
        "reports/insights/12_ai_context_pack.md",
        "Drop-in summary for pasting into an LLM along with the project.",
    ),
    ("reports/insights/13_runbook.md", "Generated setup/run/test/Docker instructions."),
    (
        "reports/insights/14_dependency_graph.md",
        "Internal import/dependency graph in Markdown.",
    ),
    (
        "reports/insights/14_dependency_graph.mmd",
        "Mermaid dependency graph for visual architecture review.",
    ),
    (
        "reports/insights/15_architecture_report.md",
        "Layered architecture map and extension points.",
    ),
    (
        "reports/insights/16_key_files_report.md",
        "Ranked list of the most important project files and reasons.",
    ),
    (
        "reports/insights/17_code_quality_report.md",
        "Maintainability review: large files, long functions, duplication, mixed responsibilities.",
    ),
    (
        "reports/insights/18_api_surface_report.md",
        "Backend route candidates and frontend HTTP call candidates.",
    ),
    (
        "reports/insights/19_frontend_report.md",
        "Frontend-specific map: components, hooks, routes, stores, forms.",
    ),
    (
        "reports/insights/20_backend_report.md",
        "Backend-specific map: API, services, models, repositories, migrations, jobs.",
    ),
    (
        "reports/insights/21_git_timeline_report.md",
        "Recent commits, contributors, and file churn in Git history.",
    ),
    (
        "reports/insights/22_project_health_report.md",
        "Project health score across architecture, security, maintainability, docs and AI readiness.",
    ),
    (
        "reports/insights/23_refactoring_opportunities.md",
        "Prioritised refactoring candidates with suggested actions.",
    ),
    (
        "reports/insights/24_architecture_map.md",
        "Layered architecture map with entry points, module responsibilities and Mermaid graph.",
    ),
    (
        "reports/insights/25_large_files_report.md",
        "Large file and folder inspector for archive-size diagnostics.",
    ),
    (
        "reports/insights/26_dependency_intelligence.md",
        "Dependency intelligence: package managers, lockfiles, runtime/dev groups and hygiene checks.",
    ),
    (
        "reports/insights/27_archive_plan.md",
        "Archive plan: single ZIP or logical split parts before writing archive files.",
    ),
    (
        "reports/insights/28_export_plan.md",
        "Pre-copy export plan: included/excluded files, warnings, large files and selected size.",
    ),
    (
        "reports/insights/29_export_comparison_report.md",
        "Incremental export comparison against the previous successful baseline.",
    ),
    (
        "reports/insights/REPORT_DASHBOARD.html",
        "Local HTML dashboard for navigating project health, security and export reports.",
    ),
    (
        "reports/insights/06_security_scan.json",
        "Machine-readable security findings JSON.",
    ),
    (
        "reports/insights/06_security_scan.sarif",
        "SARIF security findings for code-review/security tooling.",
    ),
    (
        "reports/insights/AI_CONTEXT/",
        "Multi-file AI context folder for ChatGPT/Codex handoff.",
    ),
    (
        "reports/insights/AI_PROMPTS/",
        "Ready-to-use prompts for ChatGPT/Codex review, refactoring, security and bug-hunting workflows.",
    ),
)
