from __future__ import annotations

import re
from pathlib import Path

APP_NAME = "Project Exporter Desktop"

APP_VERSION = "2.0"

SETTINGS_FILE = Path.home() / ".project_exporter_desktop.json"

IGNORED_DIR_NAMES: frozenset[str] = frozenset(
    {
        ".git",
        "node_modules",
    }
)

TEXT_EXTENSIONS: set[str] = {
    "adoc",
    "ahk",
    "asciidoc",
    "astro",
    "bash",
    "bat",
    "bib",
    "bzl",
    "c",
    "cc",
    "cfg",
    "cjs",
    "clj",
    "cljc",
    "cljs",
    "cls",
    "cmake",
    "cmd",
    "conf",
    "config",
    "cpp",
    "cs",
    "css",
    "csv",
    "cxx",
    "d",
    "dart",
    "desktop",
    "diff",
    "dockerfile",
    "dockerignore",
    "editorconfig",
    "edn",
    "ejs",
    "elm",
    "env",
    "erl",
    "err",
    "ex",
    "exs",
    "feature",
    "fish",
    "fs",
    "fsi",
    "fsx",
    "gemspec",
    "gitattributes",
    "gitignore",
    "go",
    "gql",
    "gradle",
    "graphql",
    "groovy",
    "h",
    "haml",
    "hcl",
    "hh",
    "hpp",
    "hrl",
    "hs",
    "htm",
    "html",
    "hxx",
    "ini",
    "ipynb",
    "java",
    "jl",
    "js",
    "json",
    "json5",
    "jsx",
    "kt",
    "kts",
    "less",
    "lhs",
    "lock",
    "log",
    "lua",
    "makefile",
    "md",
    "markdown",
    "mjs",
    "mk",
    "ml",
    "mli",
    "nim",
    "npmrc",
    "nvmrc",
    "odin",
    "org",
    "out",
    "patch",
    "php",
    "phtml",
    "pl",
    "pm",
    "pod",
    "properties",
    "proto",
    "ps1",
    "psm1",
    "py",
    "pyi",
    "pyw",
    "r",
    "rake",
    "rb",
    "rs",
    "rst",
    "sass",
    "scala",
    "scss",
    "sh",
    "sol",
    "sql",
    "svelte",
    "tex",
    "tf",
    "tfvars",
    "toml",
    "ts",
    "tsv",
    "tsx",
    "txt",
    "v",
    "vb",
    "vbs",
    "vue",
    "xml",
    "yaml",
    "yml",
    "zig",
    "zsh",
}

TEXT_FILENAMES_WITHOUT_EXTENSION: set[str] = {
    ".env",
    ".env.example",
    ".env.local",
    ".env.development",
    ".env.production",
    ".gitignore",
    ".gitattributes",
    ".dockerignore",
    ".editorconfig",
    ".npmrc",
    ".nvmrc",
    "dockerfile",
    "makefile",
    "readme",
    "license",
}

BINARY_EXTENSIONS: set[str] = {
    "7z",
    "a",
    "aac",
    "accdb",
    "ai",
    "aiff",
    "apk",
    "avi",
    "bin",
    "blend",
    "bmp",
    "bz2",
    "cab",
    "class",
    "db",
    "dll",
    "dmg",
    "doc",
    "docx",
    "dwg",
    "dylib",
    "ear",
    "eot",
    "epub",
    "exe",
    "fbx",
    "flac",
    "flv",
    "gif",
    "gz",
    "heic",
    "ico",
    "iso",
    "jar",
    "jpeg",
    "jpg",
    "lib",
    "m4a",
    "m4v",
    "max",
    "mdb",
    "mkv",
    "mov",
    "mp3",
    "mp4",
    "mpeg",
    "mpg",
    "o",
    "obj",
    "odp",
    "ods",
    "odt",
    "ogg",
    "opus",
    "otf",
    "pdf",
    "png",
    "ppt",
    "pptx",
    "psd",
    "pyc",
    "pyd",
    "pyo",
    "rar",
    "raw",
    "so",
    "sqlite",
    "sqlite3",
    "tar",
    "tif",
    "tiff",
    "ttf",
    "wav",
    "war",
    "webm",
    "webp",
    "wmv",
    "woff",
    "woff2",
    "wma",
    "xls",
    "xlsx",
    "xz",
    "zip",
}

TRY_ENCODINGS: tuple[str, ...] = (
    "utf-8",
    "utf-8-sig",
    "cp1251",
    "cp866",
    "utf-16",
    "latin-1",
)

_REDACT_KEYWORDS = r"API[_-]?KEY|SECRET|TOKEN|PASSWORD|PASS|PRIVATE[_-]?KEY"

_SCAN_KEYWORDS = (
    _REDACT_KEYWORDS
    + r"|DATABASE[_-]?URL|JWT[_-]?SECRET|ACCESS[_-]?KEY|CLIENT[_-]?SECRET"
)

SECRET_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(rf"(?i)\b({_REDACT_KEYWORDS})\b\s*[:=]\s*(['\"]?)[^\s'\"\n]+(\2)"),
    re.compile(r"(?i)\b(BEARER)\s+[A-Za-z0-9._\-+/=]{16,}"),
)

SECRET_KEY_PATTERN = re.compile(rf"(?i)\b({_SCAN_KEYWORDS})\b")

TODO_PATTERN = re.compile(r"(?i)\b(TODO|FIXME|HACK|XXX|BUG|TEMP|REFACTOR|DEPRECATED)\b")

MONTHS = (
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
)

LANGUAGE_BY_EXTENSION: dict[str, str] = {
    "py": "Python",
    "pyw": "Python",
    "pyi": "Python",
    "js": "JavaScript",
    "jsx": "JavaScript / React",
    "mjs": "JavaScript",
    "cjs": "JavaScript",
    "ts": "TypeScript",
    "tsx": "TypeScript / React",
    "css": "CSS",
    "scss": "SCSS",
    "sass": "Sass",
    "less": "Less",
    "html": "HTML",
    "htm": "HTML",
    "vue": "Vue",
    "svelte": "Svelte",
    "astro": "Astro",
    "go": "Go",
    "rs": "Rust",
    "java": "Java",
    "kt": "Kotlin",
    "kts": "Kotlin",
    "cs": "C#",
    "cpp": "C++",
    "cxx": "C++",
    "cc": "C++",
    "c": "C",
    "h": "C/C++ Header",
    "hpp": "C++ Header",
    "rb": "Ruby",
    "php": "PHP",
    "swift": "Swift",
    "dart": "Dart",
    "sql": "SQL",
    "sh": "Shell",
    "bash": "Shell",
    "zsh": "Shell",
    "fish": "Shell",
    "ps1": "PowerShell",
    "bat": "Batch",
    "cmd": "Batch",
    "json": "JSON",
    "json5": "JSON5",
    "yaml": "YAML",
    "yml": "YAML",
    "toml": "TOML",
    "xml": "XML",
    "md": "Markdown",
    "markdown": "Markdown",
    "rst": "reStructuredText",
    "dockerfile": "Dockerfile",
}

SOURCE_CODE_EXTENSIONS: set[str] = {
    "astro",
    "c",
    "cc",
    "cpp",
    "cs",
    "css",
    "cxx",
    "dart",
    "go",
    "h",
    "hpp",
    "html",
    "htm",
    "java",
    "js",
    "jsx",
    "kt",
    "kts",
    "less",
    "mjs",
    "php",
    "py",
    "pyi",
    "pyw",
    "rb",
    "rs",
    "sass",
    "scss",
    "sh",
    "sql",
    "svelte",
    "ts",
    "tsx",
    "vue",
}

CONFIG_FILES: tuple[str, ...] = (
    "package.json",
    "pnpm-lock.yaml",
    "package-lock.json",
    "yarn.lock",
    "bun.lockb",
    "tsconfig.json",
    "jsconfig.json",
    "vite.config.ts",
    "vite.config.js",
    "next.config.js",
    "next.config.mjs",
    "next.config.ts",
    "eslint.config.js",
    "eslint.config.mjs",
    ".eslintrc",
    ".eslintrc.js",
    ".eslintrc.json",
    ".prettierrc",
    ".prettierrc.json",
    "prettier.config.js",
    "tailwind.config.js",
    "tailwind.config.ts",
    "postcss.config.js",
    "components.json",
    "pyproject.toml",
    "requirements.txt",
    "requirements-dev.txt",
    "poetry.lock",
    "Pipfile",
    "Pipfile.lock",
    "go.mod",
    "go.sum",
    "Cargo.toml",
    "Cargo.lock",
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    ".env.example",
    ".gitignore",
    "README.md",
    "LICENSE",
)

SENSITIVE_FILENAMES: set[str] = {
    ".env",
    ".env.local",
    ".env.development",
    ".env.production",
    ".env.test",
    "id_rsa",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "credentials.json",
    "service-account.json",
    "service_account.json",
    "firebase-adminsdk.json",
}

SENSITIVE_SUFFIXES: set[str] = {
    "key",
    "pem",
    "p12",
    "pfx",
    "crt",
    "cer",
    "keystore",
    "jks",
}

REPORT_DESCRIPTIONS: tuple[tuple[str, str], ...] = (
    (
        "reports/01_structure.txt",
        "PowerShell-like directory listing of the copied project.",
    ),
    (
        "reports/02_git.txt",
        "Read-only Git snapshot from the ORIGINAL project (status, last commits).",
    ),
    (
        "reports/03_text_dump.txt",
        "Concatenated contents of every text-like file in the copy.",
    ),
    (
        "reports/insights/01_summary.txt",
        "High-level overview: stack detection, language counts, biggest files.",
    ),
    (
        "reports/insights/02_file_statistics.txt",
        "File counts by extension, deepest paths, empty / suspicious files.",
    ),
    (
        "reports/insights/03_dependencies.txt",
        "package.json / requirements.txt / go.mod / Cargo.toml dependencies.",
    ),
    (
        "reports/insights/04_scripts.txt",
        "npm/pnpm scripts, Makefile targets, Docker convenience commands.",
    ),
    (
        "reports/insights/05_git_deep.txt",
        "Extended read-only Git inspection (branches, remotes, diffs, ls-files).",
    ),
    (
        "reports/insights/06_security_scan.txt",
        "Heuristic scan for .env-like files and secret-looking lines (redacted).",
    ),
    (
        "reports/insights/07_todo_fixme.txt",
        "TODO / FIXME / HACK / XXX / DEPRECATED markers across the codebase.",
    ),
    (
        "reports/insights/08_code_metrics.txt",
        "LOC, comment ratios, files over 500 / 1000 lines.",
    ),
    (
        "reports/insights/09_config.txt",
        "Detected configuration files and capability checklist.",
    ),
    ("reports/insights/10_docker.txt", "Dockerfile / docker-compose service map."),
    (
        "reports/insights/11_routes_and_pages.txt",
        "Heuristic UI map: routes, pages, components.",
    ),
    (
        "reports/insights/12_ai_context_pack.md",
        "Drop-in summary for pasting into an LLM along with the project.",
    ),
)
